<a href="https://colab.research.google.com/github/JAMUNAASHREE18/jamunaa-codebooster1-2026/blob/main/Day3/Day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install requests --quiet
import pandas as pd
import numpy as np
import requests
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

print('All libraries imported successfully')
print(f'Pandas : {pd.__version__}')
print(f'requests: {requests.__version__}')

All libraries imported successfully
Pandas : 2.2.2
requests: 2.32.4

In [ ]:
raw_df=pd.read_csv('messy_sales_data.csv')
print(f'Raw data loaded:{raw_df.shape[0]}rows,{raw_df.shape[1]}columns')
print(f'Columns:{raw_df.columns.tolist()}')
print('print first five datas')
raw_df.head()

Raw data loaded:30rows,9columns
Columns:['order_id', 'customer_name', 'product', 'category', 'quantity', 'unit_price', 'order_date', 'city', 'sales_rep']
print first five datas

,order_id,customer_name,product,category,quantity,unit_price,order_date,city,sales_rep
0,1001,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma
1,1002,Priya Nair,NaN,Electronics,1.0,15000,2024-01-07,Delhi,Sunita Rao
2,1003,AMIT VERMA,Keyboard,Accessories,3.0,1200,2024-01-08,Bangalore,Anil Sharma
3,1004,Sunita Patel,Monitor,Electronics,NaN,22000,2024-01-10,Chennai,Ravi Kumar
4,1005,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma

In [19]:
print('=' * 55)
print(' DATA QUALITY ANALYSIS REPORT')
print('=' * 55)

#missing values 1   -- empty values get 1 and sum it up
print(' missing values per column')
print(raw_df.isnull().sum())

#duplicate rows 2   -- duplicate row get 1 and sum
print(f"\n duplicate rows {raw_df.duplicated().sum()}")

#data types
print(raw_df.dtypes)


#dropna delete the duplicate
print('\n unique category:' , raw_df['category'].unique())
print('\n sample customer name:' , raw_df['customer_name'].dropna().unique()[:8])

print('\n sample order_date values:', raw_df['order_date'].unique()[:8])

=======================================================
 DATA QUALITY ANALYSIS REPORT
=======================================================
 missing values per column
order_id         0
customer_name    2
product          1
category         1
quantity         3
unit_price       0
order_date       0
city             0
sales_rep        0
dtype: int64

 duplicate rows 0
order_id           int64
customer_name     object
product           object
category          object
quantity         float64
unit_price         int64
order_date        object
city              object
sales_rep         object
dtype: object

 unique category: ['Electronics' 'Accessories' nan]

 sample customer name: ['Ramesh Kumar' 'Priya Nair' 'AMIT VERMA' 'Sunita Patel' 'kiran mehta'
 'Deepak Singh' 'Ananya Das' 'Vikram Iyer']

 sample order_date values: ['2024-01-05' '2024-01-07' '2024-01-08' '2024-01-10' '07-01-2024'
 '2024-01-12' '2024-01-13' '2024-01-15']

In [31]:
#create the working copy  (etl best practice)
# so the original data are safe
df = raw_df.copy()

print(f'working copy created: {df.shape}')
print('raw_df is untouched - we can reset by running df = raw_df.copy()')

working copy created: (30, 9)
raw_df is untouched - we can reset by running df = raw_df.copy()

In [32]:
#fix - 1 handle missing values

print('before fixing nulls',df.isnull().sum().sum() , 'total missing values')
 # fill the missing values , makes the changes directly in the dataframe
df['customer_name'].fillna('unknown customer' , inplace= True)
median_qty = df['quantity'].median()
df['quantity'].fillna(median_qty , inplace= True)
print(f'filled missing quanity with median qty {median_qty}')

df['category'].fillna('uncategorised', inplace=True)

print('after  fixing nulls',df.isnull().sum().sum() , 'total missing values')

before fixing nulls 7 total missing values
filled missing quanity with median qty 2.0
after  fixing nulls 1 total missing values

In [33]:
# fix - 2 remove the duplicates

print(f'before deduplication {len(df)} rows')

print(f'duplicate rows {df.duplicated().sum()}')

print(df[df.duplicated(keep=False)][['order_id' , 'customer_name', 'product' , 'order_date']])

df.drop_duplicates(inplace=True)
print(f'after deduplication {len(df)} rows')
print(f'rows removed {len(raw_df)-len(df)} rows')

before deduplication 30 rows
duplicate rows 0
Empty DataFrame
Columns: [order_id, customer_name, product, order_date]
Index: []
after deduplication 30 rows
rows removed 0 rows

In [34]:
print('before fixing nulls',df['product'].isnull().sum().sum() , 'total missing values')
 # fill the missing values , makes the changes directly in the dataframe

print(df.isnull().sum())
df['product'].fillna('unknown product' , inplace= True)

print('after  fixing nulls',df['product'].isnull().sum().sum() , 'total missing values')
print(raw_df['product'].isnull().sum())
#because the code run many times there is no missing values

print(df)

before fixing nulls 1 total missing values
order_id         0
customer_name    0
product          1
category         0
quantity         0
unit_price       0
order_date       0
city             0
sales_rep        0
dtype: int64
after  fixing nulls 0 total missing values
1
    order_id     customer_name          product       category  quantity  \
0       1001      Ramesh Kumar           Laptop    Electronics       2.0
1       1002        Priya Nair  unknown product    Electronics       1.0
2       1003        AMIT VERMA         Keyboard    Accessories       3.0
3       1004      Sunita Patel          Monitor    Electronics       2.0
4       1005      Ramesh Kumar           Laptop    Electronics       2.0
5       1006       kiran mehta            Mouse    Accessories      10.0
6       1007      Deepak Singh       Headphones    Electronics       2.0
7       1008  unknown customer           Webcam    Accessories       1.0
8       1009        Ananya Das           Laptop    Electronics       1.0
9       1010       Vikram Iyer         Keyboard    Accessories       5.0
10      1011       Pooja Gupta          Monitor    Electronics       2.0
11      1012        SURESH RAO          USB Hub    Accessories       8.0
12      1013       Meera Joshi           Laptop    Electronics       2.0
13      1014        Arjun Nair       Headphones    Electronics       3.0
14      1015       Tanvi Mehta           Webcam    Accessories       2.0
15      1016       Kiran Mehta            Mouse    Accessories      10.0
16      1017      Deepak Singh         Keyboard    Accessories       5.0
17      1018       Rohit Verma          Monitor    Electronics       1.0
18      1019       Sneha Reddy           Laptop    Electronics       1.0
19      1020     Gaurav Shukla          USB Hub    Accessories      15.0
20      1021      Nisha Kapoor       Headphones    Electronics       2.0
21      1022       Ajay Tiwari           Webcam    Accessories       3.0
22      1023        ANANYA DAS           Laptop    Electronics       1.0
23      1024     Preeti Saxena         Keyboard    Electronics       4.0
24      1025         Amit Bose            Mouse    Accessories       6.0
25      1026  unknown customer       Headphones    Electronics       1.0
26      1027        Rekha Nair          Monitor  uncategorised       2.0
27      1028     Harish Pillai           Laptop    Electronics       3.0
28      1029      Sanjay Dubey          USB Hub    Accessories      10.0
29      1030     Kavya Nambiar           Webcam    Accessories       2.0

    unit_price  order_date                city    sales_rep
0        45000  2024-01-05              Mumbai  Anil Sharma
1        15000  2024-01-07               Delhi   Sunita Rao
2         1200  2024-01-08           Bangalore  Anil Sharma
3        22000  2024-01-10             Chennai   Ravi Kumar
4        45000  2024-01-05              Mumbai  Anil Sharma
5          800  07-01-2024                Pune   Sunita Rao
6         3500  2024-01-12           Hyderabad   Ravi Kumar
7         2500  2024-01-13              Mumbai  Anil Sharma
8        45000  2024-01-15             Kolkata   Sunita Rao
9         1200  2024-01-15             Chennai   Ravi Kumar
10       22000  2024-01-18               Delhi  Anil Sharma
11         600  2024-01-20           Bangalore   Sunita Rao
12       45000  2024-01-22                Pune   Ravi Kumar
13        3500  21-01-2024               Kochi  Anil Sharma
14        2500  2024-01-25               Surat   Sunita Rao
15         800  2024-01-07                Pune   Sunita Rao
16        1200  2024-01-28           Hyderabad   Ravi Kumar
17       22000  2024-01-30               Delhi  Anil Sharma
18       45000  2024-02-01           Hyderabad   Ravi Kumar
19         600  2024-02-03             Lucknow   Sunita Rao
20        3500  2024-02-05          Chandigarh  Anil Sharma
21        2500  2024-02-07              Bhopal   Ravi Kumar
22       45000  2024-01-15             Kolkata   Sunita Rao
23        1200  2024-02-10              Kanpur  Anil Sharma
24         800  2024-02-12             Kolkata   Sunita Rao
25        3500  2024-02-14              Mumbai   Ravi Kumar
26       22000  2024-02-15               Kochi  Anil Sharma
27       45000  2024-02-18  Thiruvananthapuram   Ravi Kumar
28         600  2024-02-20           Allahabad   Sunita Rao
29        2500  2024-02-22            Thrissur  Anil Sharma

In [36]:
df = pd.read_csv('messy_sales_data - messy_sales_data.csv')
print('/nprint first five data')
df.head()

/nprint first five data

,order_id,customer_name,product,category,quantity,unit_price,order_date,city,sales_rep
0,1001,Priya Nair,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma
1,1002,Priya Nair,NaN,Electronics,1.0,15000,2024-01-07,Delhi,Sunita Rao
2,1003,AMIT VERMA,Keyboard,Accessories,3.0,1200,2024-01-08,Bangalore,Anil Sharma
3,1004,Sunita Patel,Monitor,Electronics,NaN,22000,2024-01-10,Chennai,Ravi Kumar
4,1005,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma

In [40]:
# fixing the datatype
df = pd.read_csv('messy_sales_data.csv')

print('sample data before parsing')
print(df['order_date'].head(8).tolist())

df['order_date'] = pd.to_datetime(
    df['order_date'],
    dayfirst=False,
    errors='coerce'

)

nat_count = df['order_date'].isnull().sum()
print(f'unparsable date: {nat_count}')

df['year'] = df['order_date'].dt.year
df['month'] = df['order_date'].dt.month
# Change this line:
df['month_name'] = df['order_date'].dt.strftime('%B')

print(df[['order_date','year', 'month', 'month_name']].head(5))

sample data before parsing
['2024-01-05', '2024-01-07', '2024-01-08', '2024-01-10', '2024-01-05', '07-01-2024', '2024-01-12', '2024-01-13']
unparsable date: 2
  order_date    year  month month_name
0 2024-01-05  2024.0    1.0    January
1 2024-01-07  2024.0    1.0    January
2 2024-01-08  2024.0    1.0    January
3 2024-01-10  2024.0    1.0    January
4 2024-01-05  2024.0    1.0    January

In [39]:
# fixing the datatype
df = pd.read_csv('messy_sales_data.csv')

print('sample data before parsing')
print(df['order_date'].head(8).tolist())

df['order_date'] = pd.to_datetime(
    df['order_date'],
    dayfirst=True, # Set to True to correctly interpret 'DD-MM-YYYY' dates
    errors='coerce',
    format='mixed' # Use mixed format inference for heterogeneous date strings
)

nat_count = df['order_date'].isnull().sum()
print(f'unparsable date: {nat_count}')

df['year'] = df['order_date'].dt.year
df['month'] = df['order_date'].dt.month
# Change this line:
df['month_name'] = df['order_date'].dt.strftime('%B')

print(df[['order_date','year', 'month', 'month_name']].head(5))

sample data before parsing
['2024-01-05', '2024-01-07', '2024-01-08', '2024-01-10', '2024-01-05', '07-01-2024', '2024-01-12', '2024-01-13']
unparsable date: 0
  order_date  year  month month_name
0 2024-01-05  2024      1    January
1 2024-01-07  2024      1    January
2 2024-01-08  2024      1    January
3 2024-01-10  2024      1    January
4 2024-01-05  2024      1    January